# Generated by Django 4.2.11 on 2025-12-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescueteam',
            name='area_name',
        ),
        migrations.RemoveField(
            model_name='rescueteam',
            name='operating_radius',
        ),
        migrations.AddField(
            model_name='rescueteam',
            name='district',
            field=models.CharField(blank=True, default='', help_text='Quận/Huyện hoạt động', max_length=255),
        ),
        migrations.AddField(
            model_name='rescueteam',
            name='province',
            field=models.CharField(default='', help_text='Tỉnh/Thành phố hoạt động', max_length=255),
        ),
    ]
