# Generated by Django 4.2.11 on 2025-12-23 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_type', models.CharField(choices=[('flood', 'Flood'), ('fire', 'Fire'), ('earthquake', 'Earthquake'), ('storm', 'Storm'), ('accident', 'Accident'), ('medical', 'Medical Emergency'), ('other', 'Other')], max_length=50)),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
                ('images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='incidents_i_created_c4c91a_idx'), models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'), models.Index(fields=['incident_type'], name='incidents_i_inciden_337dba_idx')],
            },
        ),
    ]
